alias c="clear"
alias cat="bat -p"
alias k="kubectl"
alias v="nvim"
alias vim="nvim"
alias vimdiff="nvim -d"
alias :q="exit"
alias idokendo="tmux new -s idokendo || tmux attach -t idokendo"
alias zshprof="time ZSH_DEBUGRC=1 zsh -i -c exit"
