{ ... }:
let
  commonPackagesModule =
    { pkgs, ... }:
    {
      environment.systemPackages = with pkgs; [
        atuin
        awscli2
        bash-language-server
        bat
        clang-tools
        cmake
        cmatrix
        coreutils
        curl
        delta
        execline
        eza
        fastfetch
        fd
        ffmpeg
        fzf
        gettext
        git
        gitui
        glab
        gnupg
        gnused
        gnutls
        go
        golangci-lint
        gopls
        grpcurl
        gtypist
        gum
        helm-ls
        home-manager
        jdk
        jq
        less
        lua-language-server
        lua51Packages.jsregexp
        lua51Packages.lua
        luarocks
        neovim
        nil
        nodePackages.prettier
        nodejs
        pre-commit
        presenterm
        protobuf
        pwgen
        pyrefly
        python313Packages.sqlfmt
        ripgrep
        ruff
        rust-analyzer
        rustup
        silicon
        sqlc
        sqlite
        starship
        stow
        stylua
        telegram-desktop
        terraform
        terraform-ls
        tmux
        typescript-language-server
        typos-lsp
        unixtools.watch
        unzip
        uv
        wget
        xdg-ninja
        xh
        yaml-language-server
        yamllint
        yq
        yt-dlp
      ];
    };
in
{
  flake.nixosModules."features-packages-common" = commonPackagesModule;
  flake.darwinModules."features-packages-common" = commonPackagesModule;
}
