{
  pkgs,
  lib,
  config,
  ...
}:
{
  options = {
    packages.enable = lib.mkEnableOption "includes base packages";
  };

  config = lib.mkIf config.packages.enable {
    environment.systemPackages = with pkgs; [
      alacritty
      atuin
      awscli2
      bash-language-server
      bat
      clang-tools
      cmake
      cmatrix
      coreutils
      curl
      execline
      eza
      fastfetch
      fd
      ffmpeg
      fzf
      gettext
      git
      gitui
      glab
      gnupg
      gnused
      gnutls
      go
      golangci-lint
      gopls
      grpcurl
      gtypist
      gum
      helm-ls
      home-manager
      htmx-lsp
      jq
      less
      lua-language-server
      lua51Packages.jsregexp
      lua51Packages.lua
      luarocks
      neovim
      nil
      nodePackages.prettier
      nodejs
      pre-commit
      presenterm
      protobuf
      pwgen
      pyrefly
      python313Packages.sqlfmt
      ripgrep
      ruff
      rust-analyzer
      rustup
      silicon
      sqlc
      sqlite
      starship
      stow
      stylua
      telegram-desktop
      terraform
      terraform-ls
      tmux
      typos-lsp
      unixtools.watch
      unzip
      uv
      wget
      xdg-ninja
      xh
      yamllint
      yq
      yt-dlp
    ];
  };
}
